<%--
     Generated by ASP2ASPX 4.5. 
     ASP2ASPX home page: http://www.netcoole.com
     Original File Name: D:\Developement\Chintan\Projects\CVS\Client\check_digit.asp
--%>

<%@ Page language="C#" CodeFile="check_digit.aspx.cs" Inherits="Client.check_digit_aspx_cs" Debug="true"%>


     
