<%--
     Generated by ASP2ASPX 4.5. 
     ASP2ASPX home page: http://www.netcoole.com
     Original File Name: D:\Developement\Chintan\Projects\CVS\Client\Login.asp
--%>

<%@ Page language="C#" CodeFile="Login.aspx.cs" Inherits="Client.Login_aspx_cs" Debug="true"%>

